### ISSUE TITLE
Non-HTTPS content being loaded when page is being accessed through HTTPS

### ISSUE THREAD

**Issue by thinkl33t** [HACManchester/Website#9]
I've just set up an SSL certificate on hacman.org.uk (yay startssl), but we have issues with non-secure content being loaded on the page.

I'm pretty sure most of it can be fixed by changing our http:// links to // or relative links, but not sure if this is something that can be automated in wordpress?

I'd also like to force people to the HTTPS site for access to wp-admin and the registration page once we're happy with this :)

**Chrome Developer Tools Log:**
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2013/11/hackspace-black1.png': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2012/08/hacmannewpano2-1024x358.jpg': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2012/08/hacmannewpano-1024x416.jpg': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2013/11/hackspace-black1.png': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but ran insecure content from 'http://hacman.org.uk/wp-content/plugins/google-groups-widget/ggroup.css': this content should also be loaded over HTTPS.
Failed to load resource: the server responded with a status of 404 (Not Found) https://hacman.org.uk/wp-content/themes/melany/js/dropdown-multilevel.js?ver=3.1.1
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2013/11/hackspace-black1.png': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2012/08/hacmannewpano2-1024x358.jpg': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2012/08/hacmannewpano-1024x416.jpg': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but displayed insecure content from 'http://hacman.org.uk/wp-content/uploads/2013/11/hackspace-black1.png': this content should also be loaded over HTTPS.
The page at 'https://hacman.org.uk/' was loaded over HTTPS, but ran insecure content from 'http://hacman.org.uk/wp-content/plugins/google-groups-widget/ggroup.css': this content should also be loaded over HTTPS.

**Comment by thinkl33t** [comment]
(i can do the redirect to https for secure parts of the site in a htaccess if theres no wordpressy way of doing it built in)

**Comment by BinaryKitten** [comment]
I've fixed 90% of these by specifying the url as https:// in the settings.

The only issue left is the logo as handled in the theme. Will get that resolved as later

Kat

**Comment by thinkl33t** [comment]
Ace, thanks Kat :)

**Comment by BinaryKitten** [comment]
Fixed the final part today.
